version: "3.6"

services:
  server:
    container_name: conversation-bot-server
    build:
      context: ./core
      dockerfile: dev.Dockerfile

    env_file:
      - ./core/.env
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./core/:/app
      - ignore:/app/node_modules/

  client:
    container_name: conversation-bot-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3001:3001

volumes:
  ignore:
